language: go
go:
  - 1.8.x
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
install:
  - mkdir -p $GOPATH/bin
  - export PATH=$PATH:$HOME/gopath/bin
  - glide i
  - go get github.com/onsi/ginkgo/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

script: $GOPATH/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
